In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [2]:
df=pd.read_csv("attrition.csv")
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  PerformanceRating RelationshipSatisfaction  StockOptionLevel  \
0  ...                  3                        1                 0   
1  ...                  4                        4                 1   
2  ...                  3                        2                 0   
3  ...                  3                        3                 0   
4  ...                  3                        4                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 33 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

In [4]:
le=LabelEncoder()

In [5]:
cols=df.select_dtypes(include=["object"]).columns.tolist()
for col in cols:
    print("-----------"+col+"-----------")
    print(df[col].unique())
    df[col]=le.fit_transform(df[col])
    print(df[col].unique())

-----------Attrition-----------
['Yes' 'No']
[1 0]
-----------BusinessTravel-----------
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
[2 1 0]
-----------Department-----------
['Sales' 'Research & Development' 'Human Resources']
[2 1 0]
-----------EducationField-----------
['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
[1 4 3 2 5 0]
-----------Gender-----------
['Female' 'Male']
[0 1]
-----------JobRole-----------
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']
[7 6 2 4 0 3 8 5 1]
-----------MaritalStatus-----------
['Single' 'Married' 'Divorced']
[2 1 0]
-----------OverTime-----------
['Yes' 'No']
[1 0]


In [6]:
cols=df.columns.tolist()
for col in cols:
    print(col+": "+str(np.mean(df[col])))

Age: 36.923809523809524
Attrition: 0.16122448979591836
BusinessTravel: 1.607482993197279
DailyRate: 802.4857142857143
Department: 1.260544217687075
DistanceFromHome: 9.19251700680272
Education: 2.912925170068027
EducationField: 2.2476190476190476
EmployeeCount: 1.0
EmployeeNumber: 1024.865306122449
EnvironmentSatisfaction: 2.721768707482993
Gender: 0.6
HourlyRate: 65.89115646258503
JobInvolvement: 2.7299319727891156
JobLevel: 2.0639455782312925
JobRole: 4.458503401360544
JobSatisfaction: 2.7285714285714286
MaritalStatus: 1.0972789115646258
MonthlyIncome: 6502.931292517007
MonthlyRate: 14313.103401360544
NumCompaniesWorked: 2.6931972789115646
OverTime: 0.2829931972789116
PercentSalaryHike: 15.209523809523809
PerformanceRating: 3.1537414965986397
RelationshipSatisfaction: 2.7122448979591836
StockOptionLevel: 0.7938775510204081
TotalWorkingYears: 11.279591836734694
TrainingTimesLastYear: 2.7993197278911564
WorkLifeBalance: 2.7612244897959184
YearsAtCompany: 7.0081632653061225
YearsInCurre

- DailyRate, EmployeeNumber, MonthlyIncome, MonthlyRate should be scaled
- but lets check correlation first

In [7]:
df.corr().Attrition.sort_values()

TotalWorkingYears          -0.171063
JobLevel                   -0.169105
YearsInCurrentRole         -0.160545
MonthlyIncome              -0.159840
Age                        -0.159205
YearsWithCurrManager       -0.156199
StockOptionLevel           -0.137145
YearsAtCompany             -0.134392
JobInvolvement             -0.130016
JobSatisfaction            -0.103481
EnvironmentSatisfaction    -0.103369
WorkLifeBalance            -0.063939
TrainingTimesLastYear      -0.059478
DailyRate                  -0.056652
RelationshipSatisfaction   -0.045872
YearsSinceLastPromotion    -0.033019
Education                  -0.031373
PercentSalaryHike          -0.013478
EmployeeNumber             -0.010577
HourlyRate                 -0.006846
BusinessTravel              0.000074
PerformanceRating           0.002889
MonthlyRate                 0.015170
EducationField              0.026846
Gender                      0.029453
NumCompaniesWorked          0.043494
Department                  0.063991
J

Among 4 columns only monthly income has relatively higher correlation with attrition
so we can just ignore other 3 columns(DailyRate, EmployeeNumber, MonthlyRate) and need not to scale
##### So we will proceed in following steps
1. So we will try with all columns first
2. then we will scale those 4 columns and try with all columns
3. then we will try with columns having corr value >= 0.15

In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import train_test_split

### 1. With all columns without scaling

In [9]:
Y=df['Attrition']
X=df.drop(['Attrition'],axis=1)

In [10]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [11]:
acc_list_knn=[]
acc_list_dt=[]
for i in range(1,40):
    model_dt=DecisionTreeClassifier(max_depth=i)
    model_knn=KNeighborsClassifier(n_neighbors=i)
    model_dt.fit(x_train,y_train)
    model_knn.fit(x_train,y_train)
    y_pred_dt=model_dt.predict(x_test)
    y_pred_knn=model_knn.predict(x_test)
    acc_list_dt.append(accuracy_score(y_test,y_pred_dt))
    acc_list_knn.append(accuracy_score(y_test,y_pred_knn))
depth=np.argmax(acc_list_dt)+1
k_value=np.argmax(acc_list_knn)+1
print('max_depth=',depth,",",'n_neighbors=',k_value)

max_depth= 1 , n_neighbors= 18


In [12]:
dt=DecisionTreeClassifier(max_depth=depth)
nb=GaussianNB()
knn=KNeighborsClassifier(n_neighbors=k_value)
lr=LogisticRegression()

In [13]:
voting_classifier=VotingClassifier(estimators=[('lr',lr),('dt',dt),('knn',knn),('nb',nb)],voting='hard')
for model in (dt,nb,knn,lr,voting_classifier):
    model.fit(x_train,y_train);
    y_pred_test=model.predict(x_test)
    y_pred_train=model.predict(x_train)
    print(model.__class__.__name__,": test= ",accuracy_score(y_test,y_pred),", train= ",accuracy_score(y_train,y_pred_train))

NameError: name 'y_pred' is not defined

### 2. with all columns and with scaling 

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scalar=MinMaxScaler()
df[['DailyRate', 'EmployeeNumber', 'MonthlyIncome', 'MonthlyRate']]=scalar.fit_transform(df[['DailyRate', 'EmployeeNumber', 'MonthlyIncome', 'MonthlyRate']])

lets check mean values of each columns again

In [ ]:
cols=df.columns.tolist()
for col in cols:
    print(col+": "+str(np.mean(df[col])))

- hence all the 4 columns values are scaled down
- lets check correlation again

In [ ]:
df.corr().Attrition.sort_values()

no significant change in corr value, thats good (just distribution changed but corr remains same)

In [ ]:
Y=df['Attrition']
X=df.drop(['Attrition'],axis=1)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
acc_list_knn=[]
acc_list_dt=[]
for i in range(1,40):
    model_dt=DecisionTreeClassifier(max_depth=i)
    model_knn=KNeighborsClassifier(n_neighbors=i)
    model_dt.fit(x_train,y_train)
    model_knn.fit(x_train,y_train)
    y_pred_dt=model_dt.predict(x_test)
    y_pred_knn=model_knn.predict(x_test)
    acc_list_dt.append(accuracy_score(y_test,y_pred_dt))
    acc_list_knn.append(accuracy_score(y_test,y_pred_knn))
depth=np.argmax(acc_list_dt)+1
k_value=np.argmax(acc_list_knn)+1
print('max_depth=',depth,",",'n_neighbors=',k_value)

In [ ]:
dt=DecisionTreeClassifier(max_depth=depth)
nb=GaussianNB()
knn=KNeighborsClassifier(n_neighbors=k_value)
lr=LogisticRegression()

In [ ]:
voting_classifier=VotingClassifier(estimators=[('lr',lr),('dt',dt),('knn',knn),('nb',nb)],voting='hard')
for model in (dt,nb,knn,lr,voting_classifier):
    model.fit(x_train,y_train);
    y_pred=model.predict(x_test)
    y_pred_train=model.predict(x_train)
    print(model.__class__.__name__,": test= ",accuracy_score(y_test,y_pred),", train= ",accuracy_score(y_train,y_pred_train))

- We can see their is some improvement in the accuracy of naive bayes model, knn model, logistic model and of overall voting classifier
- Also after changing the distribution (i.e by scaling the data) the overfitting problem of naive bayes is solved

### 3.  Now with columns having corr value >= 0.15

In [ ]:
Y=df['Attrition']
X=df[["TotalWorkingYears" ,"JobLevel", "YearsInCurrentRole", "MonthlyIncome", "Age", "YearsWithCurrManager","MaritalStatus", "OverTime"]]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
acc_list_knn=[]
acc_list_dt=[]
for i in range(1,40):
    model_dt=DecisionTreeClassifier(max_depth=i)
    model_knn=KNeighborsClassifier(n_neighbors=i)
    model_dt.fit(x_train,y_train)
    model_knn.fit(x_train,y_train)
    y_pred_dt=model_dt.predict(x_test)
    y_pred_knn=model_knn.predict(x_test)
    acc_list_dt.append(accuracy_score(y_test,y_pred_dt))
    acc_list_knn.append(accuracy_score(y_test,y_pred_knn))
depth=np.argmax(acc_list_dt)+1
k_value=np.argmax(acc_list_knn)+1
print('max_depth=',depth,",",'n_neighbors=',k_value)

In [ ]:
dt=DecisionTreeClassifier(max_depth=depth)
nb=GaussianNB()
knn=KNeighborsClassifier(n_neighbors=k_value)
lr=LogisticRegression()

In [ ]:
voting_classifier=VotingClassifier(estimators=[('lr',lr),('dt',dt),('knn',knn),('nb',nb)],voting='hard')
for model in (dt,nb,knn,lr,voting_classifier):
    model.fit(x_train,y_train);
    y_pred=model.predict(x_test)
    y_pred_train=model.predict(x_train)
    print(model.__class__.__name__,": test= ",accuracy_score(y_test,y_pred),", train= ",accuracy_score(y_train,y_pred_train))

We can see a slight drop in accuracy of Logistic model and significant decrease of accuracy in naive bayes model, but we can observe that overall accuracy i.e given by voting classifier is unchanged, hence we can use less columns also to get same accuracy which decreases significant amount of computation time